version: '3'
services:
  vulnerable_app:
    build: ./vulnerable_app
    container_name: vulnerable_app
    expose:
      - "5000"

  proxy:
    build: ./proxy
    container_name: proxy
    environment:
      - ENABLE_SQLI_FILTER=1
      - ENABLE_XSS_FILTER=0
    ports:
      - "8000:8000"
    depends_on:
      - vulnerable_app

  attacker:
    build: ./attacker
    container_name: attacker
    depends_on:
      - proxy

